	db "Master Ball@"
	db "Ultra Ball@"
	db "Brightpowder@"
	db "Great Ball@"
	db "# Ball@"
	db "Teru-Sama@"
	db "Bicycle@"
	db "Moon Stone@"
	db "Antidote@"
	db "Burn Heal@"
	db "Ice Heal@"
	db "Awakening@"
	db "Parlyz Heal@"
	db "Full Restore@"
	db "Max Potion@"
	db "Hyper Potion@"
	db "Super Potion@"
	db "Potion@"
	db "Escape Rope@"
	db "Repel@"
	db "Max Elixer@"
	db "Fire Stone@"
	db "Thunderstone@"
	db "Water Stone@"
	db "Poison Guard@"
	db "Hp Up@"
	db "Protein@"
	db "Iron@"
	db "Carbos@"
	db "Lucky Punch@"
	db "Calcium@"
	db "Rare Candy@"
	db "X Accuracy@"
	db "Leaf Stone@"
	db "Metal Powder@"
	db "Nugget@"
	db "# Doll@"
	db "Full Heal@"
	db "Revive@"
	db "Max Revive@"
	db "Guard Spec.@"
	db "Super Repel@"
	db "Max Repel@"
	db "Dire Hit@"
	db "Burn Guard@"
	db "Fresh Water@"
	db "Soda Pop@"
	db "Lemonade@"
	db "X Attack@"
	db "Freeze Guard@"
	db "X Defend@"
	db "X Speed@"
	db "X Special@"
	db "Coin Case@"
	db "Itemfinder@"
	db "Teru-Sama@"
	db "Exp.Share@"
	db "Old Rod@"
	db "Good Rod@"
	db "Silver Leaf@"
	db "Super Rod@"
	db "Pp Up@"
	db "Ether@"
	db "Max Ether@"
	db "Elixer@"
	db "Red Scale@"
	db "Secretpotion@"
	db "S.S.Ticket@"
	db "Mystery Egg@"
	db "Clear Bell@"
	db "Silver Wing@"
	db "Moomoo Milk@"
	db "Quick Claw@"
	db "Psncureberry@"
	db "Gold Leaf@"
	db "Soft Sand@"
	db "Sharp Beak@"
	db "Przcureberry@"
	db "Burnt Berry@"
	db "Ice Berry@"
	db "Poison Barb@"
	db "King'S Rock@"
	db "Bitter Berry@"
	db "Mint Berry@"
	db "Red Apricorn@"
	db "Tinymushroom@"
	db "Big Mushroom@"
	db "Silverpowder@"
	db "Blu Apricorn@"
	db "Sleep Guard@"
	db "Amulet Coin@"
	db "Ylw Apricorn@"
	db "Grn Apricorn@"
	db "Cleanse Tag@"
	db "Mystic Water@"
	db "Twistedspoon@"
	db "Wht Apricorn@"
	db "Blackbelt@"
	db "Blk Apricorn@"
	db "Parlyz Guard@"
	db "Pnk Apricorn@"
	db "Blackglasses@"
	db "Slowpoketail@"
	db "Pink Bow@"
	db "Stick@"
	db "Smoke Ball@"
	db "Nevermeltice@"
	db "Magnet@"
	db "Miracleberry@"
	db "Pearl@"
	db "Big Pearl@"
	db "Everstone@"
	db "Spell Tag@"
	db "Ragecandybar@"
	db "Gs Ball@"
	db "Blue Card@"
	db "Miracle Seed@"
	db "Thick Club@"
	db "Focus Band@"
	db "Confuseguard@"
	db "Energypowder@"
	db "Energy Root@"
	db "Heal Powder@"
	db "Revival Herb@"
	db "Hard Stone@"
	db "Lucky Egg@"
	db "Card Key@"
	db "Machine Part@"
	db "Egg Ticket@"
	db "Lost Item@"
	db "Stardust@"
	db "Star Piece@"
	db "Basement Key@"
	db "Pass@"
	db "Helix Fossil@"
	db "Dome Fossil@"
	db "Old Amber@"
	db "Charcoal@"
	db "Berry Juice@"
	db "Scope Lens@"
	db "Oak'S Parcel@"
	db "Teru-Sama@"
	db "Metal Coat@"
	db "Dragon Fang@"
	db "Teru-Sama@"
	db "Leftovers@"
	db "Teru-Sama@"
	db "Teru-Sama@"
	db "Teru-Sama@"
	db "Mysteryberry@"
	db "Dragon Scale@"
	db "Berserk Gene@"
	db "Teru-Sama@"
	db "Teru-Sama@"
	db "Teru-Sama@"
	db "Sacred Ash@"
	db "Heavy Ball@"
	db "Flower Mail@"
	db "Level Ball@"
	db "Lure Ball@"
	db "Fast Ball@"
	db "Teru-Sama@"
	db "Light Ball@"
	db "Friend Ball@"
	db "Moon Ball@"
	db "Love Ball@"
	db "Normal Box@"
	db "Gorgeous Box@"
	db "Sun Stone@"
	db "Polkadot Bow@"
	db "Teru-Sama@"
	db "Up-Grade@"
	db "Berry@"
	db "Gold Berry@"
	db "Squirtbottle@"
	db "Teru-Sama@"
	db "Park Ball@"
	db "Rainbow Wing@"
	db "Teru-Sama@"
	db "Brick Piece@"
	db "Surf Mail@"
	db "Litebluemail@"
	db "Portraitmail@"
	db "Lovely Mail@"
	db "Eon Mail@"
	db "Morph Mail@"
	db "Bluesky Mail@"
	db "Music Mail@"
	db "Mirage Mail@"
	db "Teru-Sama@"
	db "Tm01@"
	db "Tm02@"
	db "Tm03@"
	db "Tm04@"
	db "Teru-Sama@"
	db "Tm05@"
	db "Tm06@"
	db "Tm07@"
	db "Tm08@"
	db "Tm09@"
	db "Tm10@"
	db "Tm11@"
	db "Tm12@"
	db "Tm13@"
	db "Tm14@"
	db "Tm15@"
	db "Tm16@"
	db "Tm17@"
	db "Tm18@"
	db "Tm19@"
	db "Tm20@"
	db "Tm21@"
	db "Tm22@"
	db "Tm23@"
	db "Tm24@"
	db "Tm25@"
	db "Tm26@"
	db "Tm27@"
	db "Tm28@"
	db "Teru-Sama@"
	db "Tm29@"
	db "Tm30@"
	db "Tm31@"
	db "Tm32@"
	db "Tm33@"
	db "Tm34@"
	db "Tm35@"
	db "Tm36@"
	db "Tm37@"
	db "Tm38@"
	db "Tm39@"
	db "Tm40@"
	db "Tm41@"
	db "Tm42@"
	db "Tm43@"
	db "Tm44@"
	db "Tm45@"
	db "Tm46@"
	db "Tm47@"
	db "Tm48@"
	db "Tm49@"
	db "Tm50@"
	db "Hm01@"
	db "Hm02@"
	db "Hm03@"
	db "Hm04@"
	db "Hm05@"
	db "Hm06@"
	db "Hm07@"
	db "Teru-Sama@"
	db "Teru-Sama@"
	db "Teru-Sama@"
	db "Teru-Sama@"
	db "Teru-Sama@"
	db "Teru-Sama@"
	db "?@"

