	db "Pound@"
	db "Karate Chop@"
	db "Doubleslap@"
	db "Gunk Shot@"
	db "Zen Headbutt@"
	db "Pay Day@"
	db "Fire Punch@"
	db "Ice Punch@"
	db "Thunderpunch@"
	db "Scratch@"
	db "Fairy Wind@"
	db "Focus Blast@"
	db "Iron Defense@"
	db "Swords Dance@"
	db "Cut@"
	db "Gust@"
	db "Wing Attack@"
	db "Whirlwind@"
	db "Fly@"
	db "Bug Buzz@"
	db "Slam@"
	db "Vine Whip@"
	db "Stomp@"
	db "Double Kick@"
	db "Mega Kick@"
	db "Flare Blitz@"
	db "Rolling Kick@"
	db "Sand Attack@"
	db "Headbutt@"
	db "Horn Attack@"
	db "Fury Attack@"
	db "Horn Drill@"
	db "Tackle@"
	db "Body Slam@"
	db "Wrap@"
	db "Take Down@"
	db "Thrash@"
	db "Double Edge@"
	db "Tail Whip@"
	db "Poison Sting@"
	db "Twineedle@"
	db "Pin Missile@"
	db "Leer@"
	db "Bite@"
	db "Growl@"
	db "Roar@"
	db "Sing@"
	db "Supersonic@"
	db "Sonicboom@"
	db "Disable@"
	db "Acid@"
	db "Ember@"
	db "Flamethrower@"
	db "Mist@"
	db "Water Gun@"
	db "Hydro Pump@"
	db "Surf@"
	db "Ice Beam@"
	db "Blizzard@"
	db "Psybeam@"
	db "Bubblebeam@"
	db "Aurora Beam@"
	db "Hyper Beam@"
	db "Peck@"
	db "Drill Peck@"
	db "Submission@"
	db "Heat Wave@"
	db "Counter@"
	db "Seismic Toss@"
	db "Strength@"
	db "Absorb@"
	db "Mega Drain@"
	db "Leech Seed@"
	db "Growth@"
	db "Razor Leaf@"
	db "Solarbeam@"
	db "Poisonpowder@"
	db "Stun Spore@"
	db "Sleep Powder@"
	db "Petal Dance@"
	db "String Shot@"
	db "Dragon Rage@"
	db "Fire Spin@"
	db "Thundershock@"
	db "Thunderbolt@"
	db "Thunder Wave@"
	db "Thunder@"
	db "Rock Throw@"
	db "Earthquake@"
	db "Fissure@"
	db "Dig@"
	db "Toxic@"
	db "Confusion@"
	db "Psychic@"
	db "Hypnosis@"
	db "Meditate@"
	db "Agility@"
	db "Quick Attack@"
	db "Rage@"
	db "Teleport@"
	db "Night Shade@"
	db "Mimic@"
	db "Screech@"
	db "Double Team@"
	db "Recover@"
	db "Harden@"
	db "Minimize@"
	db "Smokescreen@"
	db "Confuse Ray@"
	db "Withdraw@"
	db "Defense Curl@"
	db "Barrier@"
	db "Light Screen@"
	db "Haze@"
	db "Reflect@"
	db "Focus Energy@"
	db "Bide@"
	db "Metronome@"
	db "Mirror Move@"
	db "Selfdestruct@"
	db "Metal Sound@"
	db "Lick@"
	db "Dragon Pulse@"
	db "Sludge@"
	db "Bone Club@"
	db "Fire Blast@"
	db "Waterfall@"
	db "Clamp@"
	db "Swift@"
	db "Aqua Jet@"
	db "Spike Cannon@"
	db "Flash Cannon@"
	db "Amnesia@"
	db "Will-O-Wisp@"
	db "Softboiled@"
	db "Hi Jump Kick@"
	db "Glare@"
	db "Dream Eater@"
	db "Rock Polish@"
	db "Seed Bomb@"
	db "Leech Life@"
	db "Lovely Kiss@"
	db "Sky Attack@"
	db "Transform@"
	db "Bubble@"
	db "Dizzy Punch@"
	db "Spore@"
	db "Flash@"
	db "Psywave@"
	db "Splash@"
	db "Acid Armor@"
	db "Crabhammer@"
	db "Explosion@"
	db "Poison Jab@"
	db "Bonemerang@"
	db "Rest@"
	db "Rock Slide@"
	db "Hyper Fang@"
	db "Sharpen@"
	db "Conversion@"
	db "Tri Attack@"
	db "Super Fang@"
	db "Slash@"
	db "Substitute@"
	db "Struggle@"
	db "Sketch@"
	db "Wild Charge@"
	db "Thief@"
	db "X Scissor@"
	db "Mind Reader@"
	db "Nightmare@"
	db "Flame Wheel@"
	db "Iron Head@"
	db "Curse@"
	db "Flail@"
	db "Conversion2@"
	db "Aeroblast@"
	db "Cotton Spore@"
	db "Reversal@"
	db "Spite@"
	db "Powder Snow@"
	db "Protect@"
	db "Mach Punch@"
	db "Scary Face@"
	db "Feint Attack@"
	db "Sweet Kiss@"
	db "Belly Drum@"
	db "Sludge Bomb@"
	db "Mud Slap@"
	db "Octazooka@"
	db "Spikes@"
	db "Zap Cannon@"
	db "Foresight@"
	db "Destiny Bond@"
	db "Perish Song@"
	db "Icy Wind@"
	db "Air Slash@"
	db "Dark Pulse@"
	db "Earth Power@"
	db "Outrage@"
	db "Sandstorm@"
	db "Giga Drain@"
	db "Endure@"
	db "Charm@"
	db "Rollout@"
	db "False Swipe@"
	db "Swagger@"
	db "Milk Drink@"
	db "Spark@"
	db "Fury Cutter@"
	db "Steel Wing@"
	db "Mean Look@"
	db "Attract@"
	db "Sleep Talk@"
	db "Heal Bell@"
	db "Return@"
	db "Present@"
	db "Dazzlingleam@"
	db "Safeguard@"
	db "Pain Split@"
	db "Sacred Fire@"
	db "Magnitude@"
	db "Dynamicpunch@"
	db "Megahorn@"
	db "Dragonbreath@"
	db "Baton Pass@"
	db "Encore@"
	db "Pursuit@"
	db "Rapid Spin@"
	db "Nasty Plot@"
	db "Iron Tail@"
	db "Metal Claw@"
	db "Vital Throw@"
	db "Morning Sun@"
	db "Synthesis@"
	db "Moonlight@"
	db "Hidden Power@"
	db "Cross Chop@"
	db "Twister@"
	db "Rain Dance@"
	db "Sunny Day@"
	db "Crunch@"
	db "Mirror Coat@"
	db "Shadow Claw@"
	db "Extremespeed@"
	db "Ancientpower@"
	db "Shadow Ball@"
	db "Future Sight@"
	db "Rock Smash@"
	db "Whirlpool@"
	db "Drill Run@"
	db "Moonblast@"
	db "Play Rough@"
	db "Sheer Cold@"
