MewIslandF1_MapScriptHeader: 
	; trigger count
	db 0

	; callback count 
	db 0
	
MewIslandSignF1_Text: ; 0x78a52
	text "Be careful of"
	line "holes!"
	done
	
MewIslandF1Sign:
	jumptext MewIslandSignF1_Text

MewIslandF1_MapEventHeader: 
	; filler
	db 0, 0

	db 30
	warp_def $10, $0, 3, GROUP_MEWISLANDENTRANCE, MAP_MEWISLANDENTRANCE
	warp_def $3, $3, 1, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def $2, $1a, 2, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def $b, $b, 1, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def $5, $f, 2, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def $d, $17, 3, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def $7, $1a, 4, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 5, 6, 3, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def 13, 5, 3, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def 13, 6, 3, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def 7, 10, 3, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def 11, 13, 3, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def 14, 14, 3, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def 12, 16, 3, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def 9, 17, 3, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def 2, 22, 3, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def 14, 24, 3, GROUP_MEWISLANDB1, MAP_MEWISLANDB1
	warp_def 5, 5, 6, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 6, 7, 7, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 4, 8, 8, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 6, 12, 9, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 8, 17, 10, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 2, 19, 11, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 8, 21, 12, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 6, 25, 13, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 13, 24, 14, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 12, 15, 15, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 12, 10, 16, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 12, 5, 18, GROUP_MEWISLANDF2, MAP_MEWISLANDF2
	warp_def 14, 3, 19, GROUP_MEWISLANDF2, MAP_MEWISLANDF2

	; xy triggers
	db 0

	; signposts
	db 1
	signpost $d, $3, $0, MewIslandF1Sign

	; people-events
	db 0
	
